name: araya-llm

services:
  streamlit-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8501:8501
    volumes:
      - rag-tab-data:/home/araya/rag-tab-data
      - rag-txt-data:/home/araya/rag-txt-data

volumes:
  rag-tab-data:
    external: true
  rag-txt-data:
    external: true
