name: araya-llm-db-2

services:
  builder:
    build:
      context: ..
      args:
        - HOST_RAG_TAB_PATH=${RAG_TAB_PATH}
      dockerfile: docker/db-build-2.Dockerfile
    volumes:
      - rag-tab-data:/home/araya/rag-tab-data
      - rag-txt-data:/home/araya/rag-txt-data

volumes:
  rag-tab-data:
    external: true
  rag-txt-data:
    external: true
